name: audio_recorder
description: A Flutter plugin to record audio.
version: 1.0.5
homepage: https://github.com/ZaraclaJ/audio_recorder

dependencies:
  path:
  flutter:
    sdk: flutter
  file:

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    androidPackage: com.jordanalcaraz.audiorecorder.audiorecorder
    pluginClass: AudioRecorderPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  path_provider:
